version: "3"

services:
  web1:
    image: registry.local:5000/jenkins-docker-pipeline-example:latest
    container_name: web_1
    networks:
      backend:
  web2:
    image: registry.local:5000/jenkins-docker-pipeline-example:latest
    container_name: web_2
    networks:
      backend:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 9000:9000
    networks:
      backend:
      frontend:
networks:
  backend:
    internal: true
  frontend:
