version: "3"

services:
  web1:
    image: registry.local:5000/jenkins-docker-pipeline-example:latest
    container_name: web_1
    ports:
      - 9000:8000
  web2:
    image: registry.local:5000/jenkins-docker-pipeline-example:latest
    container_name: web_2
    ports:
      - 9001:8000
